name: Binaries
on: pull_request_target

permissions:
  # Needed in order to update the binaries if they've changed
  contents: write

jobs:
  # Updates the binaries for the repo and commits them to the repo.
  update-binaries:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{github.event.pull_request.head.ref}}
        repository: ${{github.event.pull_request.head.repo.full_name}}
        token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/setup-go@v3
      with:
        go-version: '1.20'
    - run: make binaries
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'Update binaries'
