# Use our own size labeler action to label our own PRs with the size of the PR.
name: Size Labeler
on: [pull_request]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  labeler:
    runs-on: [ubuntu-latest]
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - name: Labeler action
      uses: ./.
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
